- js/app.js
- manifest.json
> add firefox support

- js/app.js
- js/provider/netease.js
1. 26日起网易不能打开歌单，修正此问题
2. 如果搜索框内没有关键词，切换Tab时候不调用搜索接口
> 修正网易歌单不能打开，如果搜索框内没有关键词，切换Tab时候不调用搜索接口

- js/app.js
强迫症修复暂停时页面标题中播放图标不会改变的问题。这样一来标签页处于后台时通过标题中的图标可以方便地看到播放状态。
> 页面标题中播放图标根据播放状态而改变

- js/app.js
部分歌曲在qq音乐下 歌词中会显示 `&apos;`.例如 <Rap God > -Eminem.
对这部分符号进行了处理.
> 修复 部分歌词符号显示不正确

- js/provider/xiami.js
虾米的艺人封面获取API失效了，只会返回一张默认图片，我找到一个新的API进行了替换。
> 修复虾米的艺人封面图片 

- css/common.css
源代码设置了在detail-head-cover设置了flex: 0 0 150px;我觉得是想实现高度固定，宽度自适应的吧。所以我尝试修改实现。但是浏览器来说自适应不大会影响布局，对桌面版的布局我没法去实验。。。
歌词界面的封面我觉得居中自适应比缩放长宽更好看些。
实验专辑：https://music.163.com/#/album?id=35178609
实验艺人：https://music.163.com/#/artist?id=900347
它的封面是长方形的。
> 修改专辑及艺人界面的封面固定高度、宽度自适应，歌词界面的封面居中自适应，避免图片被压缩变形。

- css/common.css
虾米的歌单封面大小不一，有横向的又有纵向的，导致精选歌单列表排列很混乱，修改为统一高度137，居中显示封面。
> 修复虾米精选歌单因图片长宽不一导致的排列混乱

- js/provider/xiami.js
换了个API，艺人界面返回的数据有专辑信息，而且显示歌曲数目可调，初步设置为50首。也给歌单换了个API，可以获取全部歌曲信息了。
还有虾米歌词链接换对应的key了，所以进行了修改。同时trc格式的歌词中间显示会“<数字>“，将其去掉。
> 修复虾米相关一系列BUG

- css/common.css
- listen1.html
精选歌单图片增加最小宽度参数，经过测试高度136，最小宽度136，排版后显示5列，观感比较合适，同时能满足缩放后的UI自适应。原来的高度137会导致只有4列。
同时下部歌单名字太长时文字会形成三行，会被图片遮挡，修改为自适应高度避免被遮挡。
> 精选歌单图片增加最小宽度参数，歌单下部文字自适应高度，防止文字被遮挡

- css/common.css
- css/iparanoid.css
- css/origin.css
- js/provider/netease.js
- listen1.html
网易云音乐歌单超过1000首会失败，因传入id过多，数据包太大会被服务器拒绝数据。修改为拆分歌单，1000首发送一次请求获取，获取所有数据后再统一显示
具体内容可查看我的博客：[网易云音乐歌单过长无法导入](https://www.cnblogs.com/NBDWDYS2214143926/p/13384020.html)
> 修复网易云导入歌单大于1000首失败问题，更改音乐详情页背景图片

- js/app.js
避免timeRegResult[3]为undefined时出现BUG。
>  fix lyric bug

- js/provider/xiami.js
- js/vendor/mode-ecb-min.js
参考https://github.com/metowolf/Meting/blob/master/src/Meting.php 及 https://github.com/LIU9293/musicAPI/blob/master/src/xiami.js ，统一了端口代码，这个端口有歌单搜索。
虽然虾米马上就要关了，默哀。。。
PS：桌面版的未验证cookie值获取是否有BUG。
> 增加虾米歌单搜索，统一端口代码

- js/app.js
- js/bridge.js
- js/l1_player.js
- js/lowebutil.js
- js/player_thread.js
- listen1.html
- manifest.json
- manifest_firefox.json
Background player works good in browser environment, but when migrate to desktop electron, background thread is not allowed to play music. So we need to build "front" player. Besides, using front player in chrome extension is easier to debug.
we create a bridge file to manage communication between UI and player (see js/bridge.js). It supports
* get player by mode (front or background)
* listen to player event by mode
* send event by player by mode
in background mode, we use chrome mechanism to send and receive message between UI (l1player/app) and Player(player_thread.js).
in front mode, we handle it by ourself. A global frontPlayerListener Array is used to store all listener functions and call them when event is triggered.
* electron compatible
* front/background player mode switch by …
> Add "front" player

- js/player_thread.js
kiwi 浏览器不支持 mediaSession.setPositionState，影响 playerSendMessage 的执行。
> 判断 mediaSession 是否支持 setPositionState

- js/app.js
- js/l1_player.js
what is this bug?
-----------------
* when open extension homepage, player bar is empty instead of showing listen1 logo.
* after play playlist and close page, current playlist is not saved. Next time open extension, current playlist keep empty.
how to fix it?
-------------
UI and background/front player status sync is maintained by manual now instead of with help of framework. So sequence is important.
this bug happens because get status before init player status. So empty player status is always got and saved to local settings.
another bug reason is sync status before communication channel (bridge.js) finishes. So some message is missing. So we need to call sync function after addLisenter function finished.
> fix current playing list not initialized bug

- i18n/en_US.json
- i18n/fr_FR.json
- i18n/zh_CN.json
- js/app.js
- js/l1_player.js
- js/lowebutil.js
- js/player_thread.js
- listen1.html
support user choose action after click close tab. It is similar to click close button for desktop software. You can determine whether to close software or just minimize it to background.
Related technology
-------------------
There're 2 different modes for communication between UI and player. If user chooses close software after click, we use frontend mode, so player is running in same window with UI. If user chooses minimize to background, we use background player (thanks for @Dumeng work)
Limitation now
---------------
Changing from one mode from another can't take effect instantly. That's because front player and background player are two process and if we need to do that, we should pass one status to another and user can still notice music pause.
Another solution is using background …
> support close tab action setting

- js/app.js
修复由于代码更新，丢失关于咪咕翻译歌词url的bug，同时不用null判断是因为有可能值为undefined。
> 修复由于代码更新，丢失关于咪咕翻译歌词url的bug

- js/provider/xiami.js
修复艺人失效的端口，因为歌单搜索已失效，xm_cookie_get增加catch返回。
> 修复虾米部分失效端口

- js/controller/playlist.js
- js/provider/migu.js
- listen1.html
咪咕增加分类榜单和排行榜。
有点小问题：MV榜数据没有专辑信息，两个专辑榜数据没办法完全适应歌单页面，我只能将就处理。
另外，因为我不会搭建桌面版的测试环境，没有测试桌面版的兼容性。--！
> Migu add playlist filters and top playlist

- js/controller/play.js
- js/l1_player.js
- js/player_thread.js
The problem is related to two reasons.
1. after delete songs, playlist does not rerender instantly, you need move mouse to see song removed.
The reason is about data sync in angularjs. In common case, we define varible in $scope and modify it in normal funciton. $scope.varible value changed and UI is updated. But if we update this value in a callback function (maybe we add listener to some event, network response for example), the render will not be triggered. So In repo, evalAsync (or timeout, apply, this anuglar functions are same) is called to force angular rerender. But why async function modification is not updated is still a question for me. If you know, please reply to me, thanks.
One solution for fixing network request is use $http or use $q.when to wrap axios, so angularjs will …
> fix: delete track in current playing problems

- js/player_thread.js
If change song too quickly, or keep click next track, song loading time will be 15 seconds for all music files. User will see play button does not change to pause status and song is not playing.
If user open devtools, a song request is showing pending for 15 seconds. 
Browser always has limit to concurrent http request to 6 (according to specification, protect DDOS from client). So we accidently hit the limit. But indeed we only load one music file one time, so some resource is not released properly.
Digging into howler source file, there's only one API to create, Howler(). If I change html5 to false, everything goes fine, but I need to wait for the whole music file download finish and start to play music which is bad for UX. If I change html5 option on, pending happens again.
After …
> fix: pending music load for 15 secs

- src/assets/css/common.css
- src/assets/css/player.css
- src/components/SettingTitle.vue
- src/composition/settings.ts
- src/i18n/en_US.json
- src/i18n/zh_CN.json
- src/views/Settings.vue
P.S: in the now playing window, click on singer and album doesn't seem to work.
> feat: add lyric font settings

- src/assets/css/common.css
It seems that BlinkMacSystemFont is problematic on Windows, it will have a make yahei higher priority than Segoe UI. I've also move yahei to lower priority due to its lack of font weight.
> fix: font render error

- src/composition/player.ts
- src/services/l1_player.ts
Now playing status in music control has some problem.
1. when one song finishes and skip to next song, playing status would first become pause and then become playing
2. when auto switch music source, in searching period, playing status is pause, and we can't interrupt that.
The reason is former design use audio playing status as our playing status. Indeed user click play button to let player know: now playlist is playing instead of playing one song. So in brief:
User click play button to START TASK of playing, instead of playing one song.
So for more reliable control, we add new state in l1_player.js to indicate whether play task is going.
> fix: more reliable playing status

- electron_src/main.js
- electron_src/package.json
- electron_src/yarn.lock
:up: deps
P.S I've also encountered a strange bug. When the app is packaged and installed, the app won't zoom to the correct level first time.
This bug doesn't happen when running directly from script.
> feat: open 1 instance

- electron_src/package.json
- electron_src/yarn.lock
- src/views/NowPlaying.vue
🆙 deps(electron) to resolve a bug that media breaks on old machines
> fix: win control missing on nowplaying

- src/views/NowPlaying.vue
@Dumeng I tried to port your change in now playing window from #755 but there's this weird gap.
Do you have time to take a quick look?
> port nowplaying window

- src/background.ts
- src/manifest.ts
- src/provider/kugou.ts
Need to clear manifest.json in `/dist` to test availability since the rollup extension doesn't update manifest if there's already one exists
> fix: taihe cors error

- package.json
- src/rules.json
- yarn.lock
It seems that v3 now breaks normal access to bilibili due to remove origin.
We might need to find a way to limit scope of request redirects.
> fix: break bilibili website

- js/player_thread.js
BUG复现：
1. 播放歌曲 A （加载歌曲）
2. 播放歌曲 B
3. 返回播放歌曲 A，并在播放列表中点击“清空”，歌曲A仍然在播放
修复：
在清空`playList`前 执行 `stopAll()`
> fix clearPlaylist issue

- js/player_thread.js
1. 添加了随机播放列表
2. 修复了上一首产生的数组越界bug
[listen1_desktop #655](https://github.com/listen1/listen1_desktop/issues/665)
#664 #576 #523 
随机播放列表重置条件
1. 歌单长度发生改变
2. 非随机模式模式并切换歌曲后重建
**使用随机播放列表方式是由于随机播放时会有回到“上一首”的需求**
现在在发生下越界时，会回到末尾
PS.
顺序排列是一种特殊的随机结果，在曲目数<=(3~5)时，有较高的机率出现这种情况，未具体计算概率。
> feat: add random playlist

- js/controller/play.js
- listen1.html
切换到新主题后，CPU，GPU用量马上上升，切换回非现代主题后问题消失
cover-list 元素会渲染所有当前歌单的元素。因为元素会涉及较多的渲染更新（因为其属性值需要和当前播放状态同步），可能是造成计算消耗的主要原因
cover-list的用途是显示最近的歌曲封面，包括上一首，下一首，当前。为了动画过渡，还需要上一首的上一首和下一首的下一首。所以，我们采用了`staged_playlist`来维护这5首歌的列表，避免了对整个歌单进行遍历。
为了新的修改，原来使用index方式来判断是否未上一首的遍历prePlayIndex也被prevSongId代替，用来记录上一首歌曲的id。
通过在windows系统上的测试，性能问题还是存在。通过一系列的对比测试发现，主要原因在于动画的部分。
新主题使用了旋转，变形等动画效果，这些效果需要借助cpu或者gpu的计算。但之前windows系统上禁用了gpu加速，导致了如果计算渲染此类元素时，会让cpu能耗非常高。
针对这种情况，我们修改了windows系统上的设定，默认允许gpu加速功能。这样，虽然加重了gpu的负担，但是好歹能让cpu的占用率控制在合理范围内。其他可用的优化还需要进一步调查。
在桌面版测试，能看到cpu基本能和原来的持平。更多测试正在进行中。
> feat: optimize modern theme performance issue

- js/controller/play.js
- listen1.html
修复播放列表小于5首歌时的问题
问题原因：之前小于5首歌时，采用的列表key重复导致了显示问题。修复后使用了song id和index结合的方式，可以在只有一首歌的时候同样可以生成不同的key。
> fix: crash when playlist less than 5 songs in modern theme

- js/controller/navigation.js
fix https://github.com/listen1/listen1_desktop/issues/837
Also, the Gpu load issue on play still exists, when the app is playing the Gpu usage surges from 1% to 30% on my Desktop with 2080, which means a nightmare on low-end laptops. The Gpu usage will drop when it's stopped or in the background.
It seems that it's due to layer update, but I've tried disable some elements (like the circling cover) on the Playbar since they're the only element that are moving, but it didn't work. It seems that there's still something under the hood here.
Below is my complete perf log. 
[Profile-20220918T222159.zip](https://github.com/listen1/listen1_chrome_extension/files/9595821/Profile-20220918T222159.zip)
> remove ape and add web compatible formats

- css/common2.css
- listen1.html
对新主题ui布局css代码进行了一些优化改进
1. 响应式的歌单列表展示
> 根据屏幕宽度调整每行歌单数量，避免歌单封面过大
2. 对设置页面进行改进
> 之前设置页面字体间隙过大，导致用户可阅读信息过少，参考主流音乐软件布局进行了改进
3. 播放栏改进
> 之前当窗口过小时，悬停出现进度条音量时会发生布局变化
> 现在进度条和音量调节条会根据窗口宽度变换
4. 对歌单详情中歌单封面进行改进
> 合理缩小了歌单封面大小，更多空间留给歌曲
5. 对歌词样式进行了小改进
6. 窗口圆角
> optimize:Ui optimization

- js/provider/bilibili.js
The album list of bilibili site was not working, because there is not album on bilibili, but I saw that there is the same search results list as results in single part, so I make those items to getting their video parts as an album, and then, making it playable.
Maybe this not be a final solution but it works fine for me now.
> Get and play bilibili video parts as songs in album

- src/views/Playlist.vue
This error caused by the router config makes that when the hotplaylist icon is clicked the params '/' will be seen as "",but there is no exist this provider.
检查控制台错误时修正的Undefined错误,在点击精选歌单时,因为路由映射的参数为空字符串所以导致匹配不到对应的Provider,从而导致Undefined.通过修改点击精选歌单时的逻辑修正这个Error.
> <fix> Clicking hotplaylist lead undefined error

- js/provider/kuwo.js
kuwo changed its api encrypt method, `Cross` in header now is not necessary. Instead of it, add `Secret` field in header and a cookie named `Hm_Iuvt_cdb524f42f0ce19b169b8072123a4727`.
And more, kuwo fixed api to fetch some vip music play url bug. So vip music play url request is rejected. Also, you need to use new method mentioned above to get accessed.
> fix: kuwo search api, play url api error

- js/provider/qq.js
qq music doesn't response with playable song url
- qq server now changes api http method from get to post, but not check sign (todo later)
- 320kbps request for play url is rejected, downgrade to 128kpbps
- use req_1 as request sequence same as official site
> fix: qq music play error

- js/controller/play.js
- js/provider/netease.js
具体表现在歌词中会莫名多出一整行多余的时间戳，比如[这首](https://music.163.com/#/song?id=28481751)和[这首](https://music.163.com/#/song?id=498549890)（以前还见过别的，不过想不起来了，就找到这两个，欢迎补充）
~~这问题挺奇怪的，多出来的时间轴似乎没什么具体含义，也不是每首歌都有，可能是以前系统升级导致的问题？~~ 才知道 LRC 格式是允许一行有多个时间轴的……定位了一下好像是 parseLyric 函数的问题
补充：
<https://music.163.com/#/song?id=4927987>
<https://music.163.com/#/song?id=26117510>
<https://music.163.com/#/song?id=4936675>
> 修复部分网易云歌曲的歌词显示问题

- js/controller/navigation.js
- js/github.js
- js/lowebutil.js
Try fix performance issue
closes: https://github.com/listen1/listen1_desktop/issues/1293 ,
closes: https://github.com/listen1/listen1_desktop/issues/1279,
closes: https://github.com/listen1/listen1_desktop/issues/1009, 
closes: https://github.com/listen1/listen1_desktop/issues/1273,
closes: https://github.com/listen1/listen1_desktop/issues/1284
etc
Also fix electron remote issue
> Fix performance issue on new theme

- js/provider/bilibili.js
- js/provider/netease.js
After upgrade electron, search is not available for netease and bilibili for desktop app.
It seems electron use more strict cookie access when make cross domain request. Cookie should set sameSite to no-restriction instead of lax to let request bring cookie in local.
And netease has change auth method as well, now NMTID cookie should be provided, but value is not checked.
- Change cookie object sameSite field value to `no-restriction`
- Set netease NMTID cookie value
- Deep investivate for cross domain cookie policy, because chrome browser has already showed warning for that. Maybe this method would not be working in the future.
- Netease NMTID fetched from site instead of fixed value.
> fix: cookie not sent problem in desktop
