.gitignore
css/player.css
js/app.js
js/netease.js
js/qq.js
js/xiami.js
listen1.html

add a new feature to main page, click the button to load more.
could be replaced by infinite scrolling or paginate in future implementation.
By the way, I'm a bit confused about the QQ api. the implementation now  seems to updated load the list of album in different order.

scrolling by button to show album(playlist)

---

css/player.css
js/app.js
listen1.html

loading spinner while searching

---

js/app.js

支持网易个人歌单打开

---

README.md
js/app.js
js/background.js
js/loweb.js
js/provider/kugou.js
js/provider/xiami.js
listen1.html
manifest.json
manifest_firefox.json

此版本有如下两个变化：
1. 增加了酷狗音乐的支持(API选自网络，不太完美)
2. 增加了 muyu<https://github.com/mu-yu>的全局快捷键
注: API的出处没有标明，也是第一次修改别人的代码，如有不妥之处希望指正。

增加了酷狗音乐的支持

---

js/app.js
js/background.js
js/loweb.js
js/provider/bilibili.js
js/provider/netease.js
listen1.html
manifest.json
manifest_firefox.json

由于 bilibili 音频区还没有搜索功能，我现在只添加了用 au 号搜索
我不太懂 js，都是 照着改/google 的，有问题欢迎 指出/修正
我把 #156 搞乱了，重新开

bilibili 音频支持

---

.eslintrc.json
.gitignore
js/app.js
js/background.js
js/github.js
js/github_api.js
js/lastfm.js
js/loweb.js
js/lowebutil.js
js/myplaylist.js
js/oauth_callback.js
js/provider/bilibili.js
js/provider/kugou.js
js/provider/kuwo.js
js/provider/netease.js
js/provider/qq.js
js/provider/xiami.js
listen1.html
package-lock.json
package.json

Update myplaylist.js to ES6 standard.

ES6 update

---

i18n/en_US.json
i18n/zh_CN.json
js/app.js
listen1.html

/listen1/listen1_desktop/#117 issue

listen1/listen1_desktop#117 实现桌面歌词

---

i18n/en_US.json
i18n/fr_FR.json
i18n/zh_CN.json
js/app.js
js/loweb.js
js/provider/netease.js
js/provider/qq.js
listen1.html

allow choose from other source when play failed.
steps:
1. if music play without error, nothing changed.
2. if music source is not available, search for backup sources, call search function to get same track
2.1. if one backup return music url, return instantly without wait for other sources to return.
2.2. if all backup sources fail, show no copyright notice.
code modifications:
1. add bootstrap handle function with failover logic code
2. always clickable when song is not available
3. add settings to control whether using this feature.

Play failover

---

js/app.js
listen1.html

监控搜索框内容是否改变，改变则按下回车键会触发搜索。但是，如果跳转到其他页面，搜索框的内容并不会自动清空，而再次按下回车键，并不会触发搜索。
监控按键——按下回车键即会触发搜索。

修改完善顶部搜索框的触发方式

---

css/common.css
js/provider/qq.js
listen1.html

优化firefox下的滑动条显示、修改QQ音乐的图片网址，同时为避免当封面和艺人图片网址返回不正确时，不显示图片，增加显示默认图片（图片来自QQ音乐）。

优化firefox下的滑动条显示及修改QQ音乐的图片网址

---

js/provider/netease.js

> https://music.163.com/#/discover/toplist?id=2884035

netease 支持排行榜单.

---

js/provider/bilibili.js

fix bi_artist function

---

js/provider/netease.js

修复网易云手机app分享链接无法打开歌单的问题

---

js/provider/qq.js

修复搜索的一个笔误bug，将api统一改为json返回，减少数据处理步骤。

修复搜索的一个笔误bug，将api统一改为json返回，减少数据处理步骤。

---

css/common.css
listen1.html

Implement the feature request #383

Add Modal feature to Playlist

---

js/app.js

try to add preliminary .flac support https://github.com/listen1/listen1_desktop/issues/284
:warning: Some flac files works fine while some doesn't
We should try add .ape support as well.

add flac support to local music

---

i18n/en_US.json
i18n/fr_FR.json
i18n/zh_CN.json
listen1.html

- add feedback links in settings page
- fix some syntax

add feedback link

---

js/app.js

- update the returned data format to new tag reader
- add ape support
Work with https://github.com/listen1/listen1_desktop/pull/353

update data format

---

.github/workflows/eslint.yml

When the file merged into the master branch, the ESlint will be run on each pull request and push operation.

GitHub Actions ESlint workflow

---

.eslintrc.json
js/app.js
js/background.js
js/github.js
js/github_api.js
js/l1_player.js
js/lastfm.js
js/loweb.js
js/lowebutil.js
js/myplaylist.js
js/oauth_callback.js
js/player_thread.js
js/provider/bilibili.js
js/provider/kugou.js
js/provider/kuwo.js
js/provider/localmusic.js
js/provider/migu.js
js/provider/netease.js
js/provider/qq.js
js/provider/xiami.js
package-lock.json
package.json

pass eslint

---

.eslintrc.json
js/lowebutil.js
js/player_thread.js
listen1.html

- fix the background cover not showing
- update some syntax to optional chaining
https://github.com/listen1/listen1_chrome_extension/blob/57c952117e690135cb70c24d8adaddaa905e5344/listen1.html#L484
That code won't work because it can not parse the '-' between "background" and "image", also the ';' at the end

fix cover image background disappear

---

listen1.html

Temporary warning before implement #428.

Add warning for Xiami songs

---

js/loweb.js

修复因为设置区分单曲和歌单的type参数后，自动切换源失效的BUG

修复自动切换源失效的BUG

---

js/github_api.js

考虑之后选择给 github api 单独创建了一个 axios 实例, 防止修改 accept 对其他接口造成意外影响。

fix listen1/listen1_desktop#359

---

js/app.js
js/github_api.js
js/l1_player.js
js/loweb.js
js/provider/localmusic.js
manifest.json
package-lock.json
package.json

- update dep
- format code
- parse track only when it's a string
- remove media key in browser #478 
- fix package.json

chore: update syntax

---

package-lock.json
package.json

https://github.com/listen1/listen1_chrome_extension/pull/480#discussion_r583613943_

add pre-commit hook

---

.gitignore
css/common.css
js/app.js
js/loweb.js
js/provider/bilibili.js
js/provider/kugou.js
js/provider/kuwo.js
js/provider/localmusic.js
js/provider/migu.js
js/provider/netease.js
js/provider/qq.js
js/provider/xiami.js
listen1.html

Hotplaylist filter

---

js/player_thread.js

remove optional chain

---

js/player_thread.js

https://github.com/listen1/listen1_desktop/issues/396

fix adjust volume shortcut bug

---

js/app.js
package-lock.json
package.json

enable zoom in desktop
https://github.com/listen1/listen1_desktop/pull/400

enable zoom

---

js/l1_player.js

fix playlist loading issue

---

i18n/zh_CN.json
js/app.js
js/loweb.js
js/provider/xiami.js
listen1.html

refer details 
https://github.com/listen1/listen1_chrome_extension/issues/500

Deprecate xiami

---

js/provider/taihe.js
listen1.html
package-lock.json
package.json

fix: format code
chore: update eslint

fix: format code

---

js/app.js
js/l1_player.js
js/loweb.js
js/player_thread.js
js/provider/netease.js
manifest.json

main task: move loweb and its dependencies into background manifest file.
optimaze bootstrap process, do network fetching work in player_thread and notice frontend.

support background bootstrap

---

js/controller/profile.js

fix: netease title missing

---

js/provider/taihe.js

主要修复的BUG有：
1. 修复歌单歌曲只能获取50首。歌单例子：https://music.taihe.com/songlist/261858 。
2. 歌手函数采用了Promise.all，但是似乎不能及时返回数据，页面一直转圈，需要再次点击进去才能显示。因为我水平有限，就改成老实的嵌套结构了。
3. 专辑函数第二个链接并不存在，而第一个链接返回的数据里其实包含有歌曲信息，所以我进行了相应的修改。由于目前专辑歌曲没有找到超过50首的，所以不确定是否需要像歌单一样多次索取数据。
4. 完善了th_parse_url函数，目前可以打开千千音乐的分享链接了。
5. 修复了其他的小BUG。

Fix some bugs of Qianqian(Taihe) music

---

js/app.js
js/background.js
js/controller/navigation.js
js/controller/play.js
js/github.js
js/github_api.js
js/lastfm.js
listen1.html

This reverts commit 03dbdb00207a4eb620cee70cb364be22d97a7659.
due to merged pr not passed github test, revert it.

Revert "Client plugins refactor (#529)"

---

js/provider/migu.js

1. 修复需要登录才能获取咪咕播放链接，并增加码率数据。
2. 修复音乐榜和影视榜在Firefox上的不能正确获取的bug，原因是用了outerText，而firefox不支持。

Fix playurl of migu and  top list in Firefox

---

css/common.css
css/iparanoid.css
css/origin.css
js/controller/navigation.js
listen1.html

adjust many ux details to make better user experience

style: Enhance ux

---

.eslintignore
js/controller/play.js
js/provider/bilibili.js
js/provider/kugou.js
js/provider/kuwo.js
js/provider/localmusic.js
js/provider/migu.js
js/provider/netease.js
js/provider/taihe.js
js/provider/xiami.js
package-lock.json
package.json

- update codes providers to static class method to better organize code and maybe extend it from a base class in the future for better clarity.
qq is not updated because there's a ongoing pr
kuwo is not updated because there's a fetch error.
Maybe we can do that later.
- update deps

update: use static class method

---

js/provider/localmusic.js

Forgot to rename function for localmusic in the previous pr

rename localmusic function

---

css/common.css
i18n/en-US.json
i18n/fr-FR.json
i18n/zh-CN.json
i18n/zh-TC.json
js/app.js
js/controller/my_playlist.js
js/controller/navigation.js
js/l1_player.js
js/loweb.js
js/myplaylist.js
js/player_thread.js
listen1.html

related issues:
https://github.com/listen1/listen1_desktop/issues/135
https://github.com/listen1/listen1_desktop/issues/101
https://github.com/listen1/listen1_desktop/issues/404
https://github.com/listen1/listen1_desktop/issues/401
https://github.com/listen1/listen1_desktop/issues/344
https://github.com/listen1/listen1_desktop/issues/373

feat: Support drag & drop

---

css/common.css
css/reset.css
js/provider/kugou.js

feat: add border-radius to button
remove: border because it's too soft on white mode and too hard on dark mode

fix: search kugou error

---

css/common.css
i18n/en-US.json
i18n/fr-FR.json
i18n/zh-CN.json
i18n/zh-TC.json
js/controller/navigation.js
js/controller/profile.js
listen1.html

use proxy setting for desktop. 
by now, how to set proxy for chrome extension axios lib is still unknown.

feat: add proxy setting for desktop version

---

.github/workflows/eslint.yml
css/common.css

There's also a mismatch in button on upload from local file because it uses label instead of button

feat: use border radius on setting buttons

---

listen1.html

Add the favicon of  Listen1 in firefox

---

css/common.css
package-lock.json
package.json

style: change win control pos to right
build: update deps

style: change win control pos to right

---

js/player_thread.js

https://web.dev/media-session/
@listen1 can you help me test the seek to effect is working or not on macOS?

feat: add seekto actionHandler

---

js/controller/navigation.js
js/provider/localmusic.js

works with https://github.com/listen1/listen1_desktop/pull/485/commits/6121c5bb7a4326a04b4bcbd8b8fd7ef8087f73b8 from
https://github.com/listen1/listen1_desktop/pull/485

feat: local music lyric

---

src/store/modules/settings.js

It seems that I made a mistake in the latest commit.
localSetting should not be an array when passed to setbySetting

fix: setting not set after reopen

---

electron_src/main.js
electron_src/package.json
electron_src/preload.js
electron_src/store.js
electron_src/yarn.lock

fix https://github.com/electron/electron/pull/31492
refactor: extract store to a file

Fix-MediaMetadata

---

src/provider/bilibili.js
src/provider/kugou.js
src/provider/kuwo.js
src/provider/localmusic.js
src/provider/migu.js
src/provider/music_resource.ts
src/provider/myplaylist.js
src/provider/netease.js
src/provider/qq.js
src/provider/taihe.js
src/provider/xiami.js
src/services/MediaService.ts

code style under `provider` folder is `my_function_1` style, for code style consistency, this pr will change them into camel style.

refactor: camel style for code under provider folder

---

src/assets/css/common.css
src/views/Home.vue
src/views/Playlist.vue
src/views/Search.vue

fix: 
* sidebar selected color error when clicked in white mode
* playlist feather icon error
* odd/even style not show in playlist page, search page
* playlist track action hover title i18n error

fix: several style errors

---

src/assets/css/common.css
src/assets/css/iparanoid.css
src/assets/css/origin.css
src/components/Href.vue
src/components/Sidebar.vue
src/composition/settings.ts
src/views/Home.vue

The current lyric is just too small in any perspecitve.

style: add font-weight on lyric

---

src/components/Modal.vue
src/components/Sidebar.vue
src/components/modals/CreatePlaylist.vue
src/components/modals/DefaultModal.vue
src/components/modals/EditPlaylist.vue
src/components/modals/ImportPlaylist.vue
src/components/modals/ParseUrl.vue
src/provider/bilibili.js
src/provider/kugou.js
src/provider/kuwo.js
src/provider/localmusic.js
src/provider/migu.js
src/provider/myplaylist.js
src/provider/netease.js
src/provider/qq.js
src/provider/taihe.js
src/provider/xiami.js
src/services/MediaService.ts
src/views/Home.vue
src/views/Playlist.vue

playlist modals migrate from dialog to modal
(maybe) use ref as playlist state container instead of event bus notify : future pr

feat: playlist modals 

---

electron_src/main.js
src/components/Sidebar.vue
src/components/modals/AddToPlaylist.vue
src/components/modals/ImportPlaylist.vue
src/provider/myplaylist.js
src/views/Home.vue

* fix ts compile error
* Repeat one not working
* playlist rename not update sidebar playlist name
* close window will shutdown app

fix: ts error when run build:electron

---

src/components/DragDropZone.vue
src/components/Sidebar.vue
src/components/modals/AddToPlaylist.vue
src/provider/myplaylist.js
src/services/MediaService.ts
src/views/Playlist.vue

related issue: #694 
Tasks Todo:

feat: V3 drag drop

---

electron_src/main.js

I'm always having error running ` MediaService.getPlaylist(listId);` maybe it's not initialized.

feat: add cover img

---

electron_src/main.js
electron_src/package.json
electron_src/store.js
electron_src/yarn.lock
src/views/Home.vue

feat: zoom in desktop
:up: deps

fix: windows  button position

---

electron_src/main.js
electron_src/package.json
electron_src/preload.js
electron_src/readtag.js
electron_src/yarn.lock
src/components/Sidebar.vue
src/env.ts
src/provider/localmusic.js
src/services/DBService.ts
src/services/MediaService.ts
src/views/Playlist.vue

feat: V3 local music

---

electron_src/main.js
src/provider/lowebutil.js
src/services/DBService.ts
src/views/Home.vue

My theme is null when I use safeGet for some weird reason. Also I still get:
in local music.

fix: minor fixes cover img for local music

---

electron_src/main.js
package.json
src/components/Playerbar.vue
src/provider/localmusic.js
yarn.lock

fix: nav bar max need double click

feat: dynamic volume icon

---

css/common.css

fix: 修复音乐分类按钮多行显示没有间距#726

---

src/App.vue
src/assets/css/common.css
src/components/DragDropZone.vue
src/components/Playerbar.vue
src/components/Sidebar.vue
src/components/modals/AddToPlaylist.vue
src/components/modals/ImportPlaylist.vue
src/composition/redheart.ts
src/provider/myplaylist.js
src/services/DBService.ts
src/views/Playlist.vue

* create red heart playlist as one of default playlists
* show whether track in red heart in playlist page, player bar
* toggle red heart status anywhere, sync states

feat: V3 red heart

---

.prettierignore
package.json
src/components/IconButton.vue
src/components/PlayerbarPopup.vue
src/components/SettingButton.vue
src/components/SidebarEntry.vue
src/views/Home.vue
src/views/NowPlaying.vue
src/views/Settings.vue
yarn.lock

- Use a consistent 4px border radius on in page element (i.e., buttons) and 8px on windows or dialogs.
- 🆙  tailwindcss
- Also, my netease tab seem completely messed up with cover with unrestricted size.

use consitent border radius

---

src/composition/player.ts
src/i18n/index.ts
src/provider/bilibili.js
src/provider/kugou.js
src/provider/kuwo.js
src/provider/migu.js
src/provider/music_resource.ts
src/provider/netease.js
src/provider/qq.js
src/provider/taihe.js
src/services/MediaService.ts
src/services/l1_player.ts
src/views/NowPlaying.vue
src/views/Playlist.vue

Add comment list in now playing page. Support hotest/newest order, pagination.
Finish comment api for all platforms and basic hotest comment list show. 
Pagination/Order is not supported.
Still consider add checkbox in settings to disable comment function (some users prefer pure music playing)
* qq: comment list include emoji tag not parsed to image
* qq: some comment includes \\n not convert to return line
* migu: comment avatar image error
洛雪音乐播放器：https://github.com/lyswhut/lx-music-desktop
Most of comment related code is refered from repo. After merged, I'll add it to readme docs.
BTW, it's best open source music player codebase I found so far.

feat: V3 comment

---

src/assets/css/themes/origin.css
src/components/WindowControl.vue
src/views/Home.vue

Adjust window control button to windows style.
Change theme origin border color.

feat: v3 change window control style to windows platform

---

src/components/DragDropZone.vue
src/components/IconButton.vue
src/components/Modal.vue
src/components/Playerbar.vue
src/components/PlayerbarPopup.vue
src/components/PlaylistGrid.vue
src/components/Sidebar.vue
src/components/TrackRow.vue
src/components/Volumebar.vue
src/components/modals/AddToPlaylist.vue
src/components/modals/CreatePlaylist.vue
src/components/modals/EditPlaylist.vue
src/components/modals/GistImport.vue
src/components/modals/ImportPlaylist.vue
src/components/modals/ParseUrl.vue
src/views/Home.vue
src/views/HotPlaylists.vue
src/views/Login.vue
src/views/MyPlatform.vue
src/views/NowPlaying.vue
src/views/Playlist.vue
src/views/Search.vue
src/views/Settings.vue

ESlint Autofixes

---

src/components/Modal.vue
src/components/Playerbar.vue
src/components/SettingButton.vue
src/components/modals/DefaultModal.vue
src/components/modals/GistExport.vue
src/components/modals/GistImport.vue
src/components/modals/GithubAuth.vue
src/components/modals/ImportPlaylist.vue
src/views/Settings.vue

fix: github status not updated

---

electron_src/float_window.js
electron_src/floatingWindow.html
electron_src/main.js
electron_src/preload.js

After some investigation on the bug of desktop lyric display on Windows. https://github.com/listen1/listen1_desktop/issues/627

fix: desktop lyric error due to fail import

---

src/components/Sidebar.vue
src/services/MediaService.ts

fix: eslint error

---

src/provider/kugou.ts

P.S we should also release a v2.22.0 for desktop as well to include that fix

chore: port 056d12d44 from master

---

src/components/PlaylistGrid.vue
src/services/GithubService.ts
src/services/MediaService.ts

fix: black square corners on white background

style: add hover effect to playlist grid

---

js/controller/navigation.js
listen1.html

feat: add double click list to play

---

js/controller/navigation.js
listen1.html

为播放列表添加双击播放
之前  #829 是歌单和搜索结果列表，补充遗漏的播放列表

feat: add double click to play for playlist

---

js/controller/navigation.js

close https://github.com/listen1/listen1_desktop/issues/678

feat: add wav support

---

js/background.js
manifest.json
manifest_firefox.json

qq api also seem to be broken ref #885

fix: taihe cors

---

js/player_thread.js

修复listen1_desktop上提出的issue：[[bug]开启一段时间后无法播放](https://github.com/listen1/listen1_desktop/issues/797)
（并没实际测试过，我本地编译不了）

remove currentHowl from playlist when url expires

---

js/controller/navigation.js

fix: bilibli search

---

css/common2.css

1. fix:新主题因窗口大小而出现元素一直触发hover特效的问题
2. fix:侧边栏hover状态一直是指针问题

fix:hover stroboscopic problem

---

css/common2.css
listen1.html

style: modern black lyric bg
close #974

style: restrict aspect ratio for play button

---

js/provider/qq.js

支持qq音乐使用更高音质

---

listen1.html

Detail:White theme now can switching icon direction when mouse hover on the track cover.
简约白主题时鼠标在正在播放的歌曲时箭头的指向在展开歌词和收起时方向改变.符合直觉.

style: fix track expand icon when hover

---

js/player_thread.js

fix: Lastfm does not record songs

---

js/provider/kuwo.js

fix: kuwo search API；

---

README_EN.md

I really enjoyed using this project, nice work! Caught a couple of typos in the README_EN.md though 😛

Update README_EN.md, fix typo(s)
